expertise_faq:
    type: rest
    resource: Puzzle\Api\ExpertiseBundle\Controller\FaqController

expertise_partner:
    type: rest
    resource: Puzzle\Api\ExpertiseBundle\Controller\PartnerController

expertise_testimonial:
    type: rest
    resource: Puzzle\Api\ExpertiseBundle\Controller\TestimonialController

expertise_service:
    type: rest
    resource: Puzzle\Api\ExpertiseBundle\Controller\ServiceController